-- Migration: 005_create_agent_jobs
-- Description: Create agent_jobs table for Level 2 Agent state and reasoning persistence
-- Target Database: Central DB (dms_admin_db)
-- Created: 2025-12-30

-- Create agent_jobs table for autonomous agent tracking
CREATE TABLE IF NOT EXISTS public.agent_jobs (
    -- Primary identification
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id VARCHAR(255) NOT NULL,
    job_type VARCHAR(100) NOT NULL,
    goal TEXT NOT NULL,

    -- State tracking
    status VARCHAR(50) NOT NULL DEFAULT 'pending',
    current_step INTEGER DEFAULT 0,
    checklist JSONB DEFAULT '[]'::jsonb,

    -- Context Ledger (Long-term memory)
    context_summary TEXT,
    reasoning_trace JSONB DEFAULT '[]'::jsonb,

    -- Session State (Short-term memory)
    session_state JSONB DEFAULT '{}'::jsonb,
    last_thoughts JSONB DEFAULT '[]'::jsonb,

    -- Execution control
    retry_count INTEGER NOT NULL DEFAULT 0,
    max_retries INTEGER NOT NULL DEFAULT 5,
    max_iterations INTEGER NOT NULL DEFAULT 20,
    iteration_count INTEGER NOT NULL DEFAULT 0,
    last_error TEXT,
    process_after TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    -- Timing
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    started_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,

    -- Source tracking (link to original communication_jobs if applicable)
    source_job_id BIGINT REFERENCES public.communication_jobs(id),
    source_reference VARCHAR(255),

    -- Human handoff
    waiting_for_human BOOLEAN DEFAULT FALSE,
    human_prompt TEXT,
    human_response TEXT,

    CONSTRAINT chk_agent_jobs_status CHECK (
        status IN ('pending', 'in_progress', 'waiting_human', 'resolved', 'failed', 'cancelled')
    )
);

-- Add table comments
COMMENT ON TABLE public.agent_jobs IS 'Job queue for Level 2 autonomous agent with reasoning and state persistence';
COMMENT ON COLUMN public.agent_jobs.job_type IS 'High-level goal type: communication, scheduling, remediation, etc.';
COMMENT ON COLUMN public.agent_jobs.goal IS 'Human-readable description of what the agent should achieve';
COMMENT ON COLUMN public.agent_jobs.checklist IS 'Dynamic task list generated by agent, JSON array of steps';
COMMENT ON COLUMN public.agent_jobs.context_summary IS 'LLM-generated summary for hydrating next session';
COMMENT ON COLUMN public.agent_jobs.reasoning_trace IS 'Full Thought/Action/Observation history for audit';
COMMENT ON COLUMN public.agent_jobs.session_state IS 'Current session variables and scratchpad';
COMMENT ON COLUMN public.agent_jobs.last_thoughts IS 'Last 5-10 thoughts for context window management';
COMMENT ON COLUMN public.agent_jobs.max_iterations IS 'Maximum ReAct loop iterations to prevent runaway';
COMMENT ON COLUMN public.agent_jobs.waiting_for_human IS 'Flag indicating agent needs human input';
COMMENT ON COLUMN public.agent_jobs.human_prompt IS 'Question or request for human operator';

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_agent_jobs_status_process_after
    ON public.agent_jobs (status, process_after)
    WHERE status IN ('pending', 'in_progress');

CREATE INDEX IF NOT EXISTS idx_agent_jobs_tenant_id
    ON public.agent_jobs (tenant_id);

CREATE INDEX IF NOT EXISTS idx_agent_jobs_created_at
    ON public.agent_jobs (created_at);

CREATE INDEX IF NOT EXISTS idx_agent_jobs_job_type
    ON public.agent_jobs (job_type);

CREATE INDEX IF NOT EXISTS idx_agent_jobs_waiting_human
    ON public.agent_jobs (tenant_id, status)
    WHERE waiting_for_human = TRUE;

CREATE INDEX IF NOT EXISTS idx_agent_jobs_source
    ON public.agent_jobs (source_job_id)
    WHERE source_job_id IS NOT NULL;

-- Create trigger for auto-updating updated_at
CREATE OR REPLACE FUNCTION public.update_agent_jobs_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_agent_jobs_updated_at ON public.agent_jobs;
CREATE TRIGGER update_agent_jobs_updated_at
    BEFORE UPDATE ON public.agent_jobs
    FOR EACH ROW
    EXECUTE FUNCTION public.update_agent_jobs_updated_at();
